# Created by extended:clip
# list as many format sections you want under formats:
# each format section requires a default template that should be modified and
# also requires a unique number for the priority higher number = lower priority
# ex: guest-100, owner-1
#   YOU MUST KEEP A default TEMPLATE! It is used when players have no other template assigned!
#   
# example format template:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Guest&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Guest'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Guest'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% '
#     suffix_click_command: ''
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Member'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Member'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% '
#     suffix_click_command: ''
check_updates: true
bungeecord:
  enabled: false
  servername: '&8[&cServer&8]'
  join_global: true
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy HH:mm:ss
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
chat_filter:
  enabled: false
  ignore_case: true
  list:
  - '.; '
  - fuck;fuck
private_message:
  enabled: true
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7You &e-> &7%recipient_player_name% &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player_name% &e-> &7You &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_groupprefix%&7] '
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player_name%'
    - '&bRank: %vault_group%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks'
    prefix_click_command: /ranks'
    name_click_command: '/msg %player_name% '
    suffix_click_command: ''
