# Erstellt von extended:clip
# Übersetzt von Andre_601 (https://andre601.com)
#
# Du kannst so viele Formate erstellen, wie du willst.
# Stelle sicher, dass diese unter "formats:" gelistet sind und folgendes haben:
# - Einen einzigartigen namen (Du kannst z.B. nicht zwei Formate mit dem namen "memeber" haben).
# - Eine Priorität (Unter "priority"). Hohe Nummer = niedrigere Priorität.
#
# Du MUSST ein Format mit dem namen default haben!
# Dieses Format wird verwendet, wenn der Spieler keine anderen verfügbar hat.
#
# Einem Spieler/Einer Gruppe gibst du ein Format mit der permission chatformat.<format name>
# Gib der Standard-Gruppe die permission chatformat.default (Diese wird nicht automatisch gegeben)
#   
# Beispiel für Formate:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Gast&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bist ein Gast'
#     prefix_tooltip:
#     - '&7%player_name% &bist ein Gast'
#     name_tooltip: [] # Setze [], wenn du keinen Hovertext willst.
#     suffix_tooltip: []
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% ' # Der placeholder wird zum Namen vom SENDER geändert.
#     suffix_click_command: ''
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bist ein Member'
#     prefix_tooltip:
#     - '&7%player_name% &bist ein Member'
#     name_tooltip: []
#     suffix_tooltip: []
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% '
#     suffix_click_command: ''
check_updates: true
bungeecord:
  enabled: false
  servername: '&8[&cServer&8]'
  join_global: true
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy HH:mm:ss
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
chat_filter:
  enabled: false
  ignore_case: true
  list:
  - '.; '
  - fuck;fuck
private_message:
  enabled: true
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7Du &e-> &7%recipient_player_name% &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player_name% &e-> &7Du &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cspy&8] &f%player_name% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_groupprefix%&7] '
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player_name%'
    - '&bRang: %vault_group%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks'
    prefix_click_command: /ranks'
    name_click_command: '/msg %player_name% '
    suffix_click_command: ''
